import type { NextPage } from "next";
import Head from "next/head";
import Login from "./login";

const Home: NextPage = () => {
  return (
    <div className="h-screen flex justify-center items-center sm:py-8">
      <Head>
        <title>Controller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/logo_controller.png" />
      </Head>
      <Login />
    </div>
  );
};

export default Home;
